name: CI/CD Pipeline

# Trigger the workflow on push to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose other environments if needed

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java (for Java projects)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # You can specify other versions if needed

      # Step 3: Install dependencies (e.g., for Maven)
      - name: Install Dependencies
        run: mvn install

      # Step 4: Run tests
      - name: Run Tests
        run: mvn test

