name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install launchable-cli # Install Launchable CLI
          mvn install # Install project dependencies

      - name: Authenticate Launchable
        run: launchable configure --token ${{ secrets.LAUNCHABLE_TOKEN }} # Authenticate using a secret

      - name: Record Build
        run: launchable record build --name ${{ github.sha }} # Record the build using the Git commit hash

      - name: Run Full Test Suite
        run: mvn test

      - name: Record Test Results
        run: launchable record tests --build ${{ github.sha }} target/surefire-reports/*.xml # Upload test results

      - name: Subset Tests (Optional)
        run: |
          launchable subset --build ${{ github.sha }} --target 30% > subset_tests.txt
          mvn test -Dsurefire.includes=$(cat subset_tests.txt) # Run the subset tests
